index:
    path: /
    controller: App\Controller\AccueilController::index

articles:
    path: /articles
    controller: App\Controller\ArticlesController::index

a-propos:
    path: /a-propos
    controller: App\Controller\AproposController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index